services:

  server:
    build:
      dockerfile: vsomeip.dockerfile
    working_dir: /vsomeip/build/examples
    command: "iperf3 -s -B 239.255.0.1 -i 1"
    networks:
      multicast_network:
        ipv4_address: 10.1.2.15

  client:
    build:
      dockerfile: vsomeip.dockerfile
    working_dir: /vsomeip/build/examples
    command: "iperf3 -c 239.255.0.1 -u -T 32 -t 10"
    networks:
      multicast_network:
        ipv4_address: 10.1.2.17

networks:
  multicast_network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_multicast: "true"      
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/16
